# Site settings
title: Michelle A. Berry
email: michberr8@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl:  https://michberr.github.io # the subpath of your site, e.g. /blog/
url:  https://michberr.github.io # the base hostname & protocol for your site
twitter_username: mich_berr
github_username:  michberr

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
# paginate: 15
# paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


